version: '2'

services:
    app:
        build: .
        container_name: react_sandbox
        ports:
            - 8080:8080
        volumes:
            - .:/app
            - /app/node_modules
        tty: true
